// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa5cAXBe0kIOOdG9liB-715GY9YtXWA4U',
    appId: '1:359221142225:web:64f3f02dda1fc7a5abdbf0',
    messagingSenderId: '359221142225',
    projectId: 'fire-login-40fb5',
    authDomain: 'fire-login-40fb5.firebaseapp.com',
    storageBucket: 'fire-login-40fb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeLk_VratzaS-Z9HF1JVTIXDouUZVy-LM',
    appId: '1:359221142225:android:6901061592bb93e1abdbf0',
    messagingSenderId: '359221142225',
    projectId: 'fire-login-40fb5',
    storageBucket: 'fire-login-40fb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6K53kSlpsBugesajlN8h6GcEYG33u0I',
    appId: '1:359221142225:ios:316e5f67e1eb08d4abdbf0',
    messagingSenderId: '359221142225',
    projectId: 'fire-login-40fb5',
    storageBucket: 'fire-login-40fb5.appspot.com',
    iosClientId: '359221142225-akg3r4moqqcmuerarcenlbvjdar23ifr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf6K53kSlpsBugesajlN8h6GcEYG33u0I',
    appId: '1:359221142225:ios:316e5f67e1eb08d4abdbf0',
    messagingSenderId: '359221142225',
    projectId: 'fire-login-40fb5',
    storageBucket: 'fire-login-40fb5.appspot.com',
    iosClientId: '359221142225-akg3r4moqqcmuerarcenlbvjdar23ifr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );
}
